# Generated by Django 4.0.4 on 2022-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
